services:
  - type: web
    name: atisunya-crm
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://atisunyacrm.onrender.com
